### PR TITLE
this is a bunch of changes

### PR DESCRIPTION
**Pull request by the-real-oliverf**
@erikwright

[Review on Reviewable](https://reviewable.io/reviews/oliver-fisher/home/6)

### CODE REVIEW

**Comment by erikwright** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[home/.bash/git.bash, line 12 [r1]](https://reviewable.io:443/reviews/oliver-fisher/home/6#-K2hrgHuiWAo0DMkjtF-)** ([raw file](https://github.com/oliver-fisher/home/blob/22707a75b6f5a9e123765b43dff194c05f83f267/home/.bash/git.bash#L12)):</sup>
Can you avoid duplicating the string PATH? DRY.



---

<sup>**[home/.bash/ruby.bash, line 8 [r1]](https://reviewable.io:443/reviews/oliver-fisher/home/6#-K2hrt-EffTlT3m0mqZr)** ([raw file](https://github.com/oliver-fisher/home/blob/22707a75b6f5a9e123765b43dff194c05f83f267/home/.bash/ruby.bash#L8)):</sup>
Are you sure about this?



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/oliver-fisher/home/6)

**Comment by the-real-oliverf** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[home/.bash/git.bash, line 12 [r1]](https://reviewable.io:443/reviews/oliver-fisher/home/6#-K2hrgHuiWAo0DMkjtF-)** ([raw file](https://github.com/oliver-fisher/home/blob/22707a75b6f5a9e123765b43dff194c05f83f267/home/.bash/git.bash#L12)):</sup>
Done.



---

<sup>**[home/.bash/ruby.bash, line 8 [r1]](https://reviewable.io:443/reviews/oliver-fisher/home/6#-K2hrt-EffTlT3m0mqZr)** ([raw file](https://github.com/oliver-fisher/home/blob/22707a75b6f5a9e123765b43dff194c05f83f267/home/.bash/ruby.bash#L8)):</sup>
Yes :+1:



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/oliver-fisher/home/6)

**Comment by erikwright** [comment]
Reviewed 2 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[home/.gitconfig, line 33 [r2]](https://reviewable.io:443/reviews/oliver-fisher/home/6#-K2hu4DQqLQXAJGnSw9l)** ([raw file](https://github.com/oliver-fisher/home/blob/4dd9cb3572246d8782e30c7f60bc341f96b5fd30/home/.gitconfig#L33)):</sup>
Rebase this please.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/oliver-fisher/home/6)

**Comment by erikwright** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[home/.gitconfig, line 33 [r2]](https://reviewable.io:443/reviews/oliver-fisher/home/6#-K2hu4DQqLQXAJGnSw9l)** ([raw file](https://github.com/oliver-fisher/home/blob/4dd9cb3572246d8782e30c7f60bc341f96b5fd30/home/.gitconfig#L33)):</sup>
I mean it. Thanks.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/oliver-fisher/home/6)

**Comment by the-real-oliverf** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[home/.gitconfig, line 33 [r2]](https://reviewable.io:443/reviews/oliver-fisher/home/6#-K2hu4DQqLQXAJGnSw9l)** ([raw file](https://github.com/oliver-fisher/home/blob/4dd9cb3572246d8782e30c7f60bc341f96b5fd30/home/.gitconfig#L33)):</sup>
Done.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/oliver-fisher/home/6)

**Comment by erikwright** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/oliver-fisher/home/6)

**Comment by erikwright** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/oliver-fisher/home/6)

**Comment by erikwright** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/oliver-fisher/home/6)

**Comment by erikwright** [comment]
<sup>**[home/.gitconfig, line 33 [r2]](https://reviewable.io:443/reviews/oliver-fisher/home/6#-K2hu4DQqLQXAJGnSw9l)** ([raw file](https://github.com/oliver-fisher/home/blob/4dd9cb3572246d8782e30c7f60bc341f96b5fd30/home/.gitconfig#L33)):</sup>
Hold on I need to think about this.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/oliver-fisher/home/6)

**Comment by the-real-oliverf** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

<sup>**[home/.gitconfig, line 33 [r2]](https://reviewable.io:443/reviews/oliver-fisher/home/6#-K2hu4DQqLQXAJGnSw9l)** ([raw file](https://github.com/oliver-fisher/home/blob/4dd9cb3572246d8782e30c7f60bc341f96b5fd30/home/.gitconfig#L33)):</sup>
Done.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/oliver-fisher/home/6)

**Pull request merged**
